### ISSUE TITLE
Contradiction with the WoT Profile spec on protocol bindings

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-architecture#850]
> [Protocol Bindings](https://w3c.github.io/wot-architecture/#dfn-wot-protocol-binding) MUST be serialized as [hypermedia controls](https://w3c.github.io/wot-architecture/#sec-hypermedia-controls) to be self-descriptive on how to activate the [Interaction Affordance](https://w3c.github.io/wot-architecture/#dfn-interaction-affordance).

I suggest changing this assertion to reflect the fact that protocol bindings can also be defined in profiles.

See also:
- https://github.com/w3c/wot-profile/issues/299 (WoT Profile)
- https://github.com/w3c/wot-thing-description/issues/1674 (WoT Thing Description)

**Comment by mlagally** [comment]
@benfrancis 
Thanks very much for this proposal.
I completely agree - we should fix the architecture spec accordingly.

**Comment by mmccool** [comment]
I might be good to word this as broadly as possible so that profiles can be one of several ways that "implied" defaults or conventions related to a protocol can be associated with an endpoint.  I seem to recall this particular assertion was also one that we were having problems gathering test input due to people not understanding the term "hypermedia".

I'd like to propose something like the following: "[Protocol Bindings](https://w3c.github.io/wot-architecture/#dfn-wot-protocol-binding) MUST be serialized in such a way that they are self-descriptive or otherwise clearly associated with definitions that indicate how to activate the [Interaction Affordance](https://w3c.github.io/wot-architecture/#dfn-interaction-affordance)."

Then profiles would be one way to "clearly associate definitions" with a Protocol binding.  Putting in explicit vocabulary terms for headers etc. and providing explicit values for them would be another.  I suggest we avoid the term "hypermedia" completely (technically vocabulary terms included in extensions are links and so "hypermedia" but...) since it just seems to confuse people.

**Comment by mmccool** [comment]
I see the PR @mlagally just adds "or Profiles".  I'll link my above comment to the PR since I think being more generic is more appropriate here.

**Comment by mlagally** [comment]
We concluded this discussion several weeks ago. Propose closing.

**Comment by benfrancis** [comment]
What was the conclusion? As far as I can tell the contradiction still exists.

Note that https://github.com/w3c/wot-thing-description/issues/1674#issuecomment-1290647125 assumes this will be addressed in the WoT Architecture specification.

**Comment by mlagally** [comment]
Arch call on Nov 30:
@benfrancis Is there a concrete proposal how to resolve this.

**Comment by mlagally** [comment]
Arch call on Nov 30:
@benfrancis Is there a concrete proposal how to resolve this?
